name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**


jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: ahmedraslan
          POSTGRES_USER : ahmedraslan
          POSTGRES_DB : customer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit\Integration Tests with Maven
        run: mvn -ntp -B verify
#        -ntp for not showing the logs for downloaded packages
#        -B run in non-interactive mode, disable output color
